version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2700:2700"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=synapse
      - DB_URL=postgres://user:password@db:5432/synapse
      - NODE_ENV=dev
      - PORT=2700
      - JWT_SECRET=JWT_SECRET
      - REDIS_URL=redis://redis:6379
      - S3_ACCESS_KEY=YOUR_S3_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=YOUR_S3_SECRET_ACCESS_KEY
      - CLOUD_FRONT_DOMAIN=YOUR_CLOUD_FRONT_DOMAIN
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
